# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da0657dc98bb751622db46b1061eec3af7279a4448009f2cc94cdcfdfc47b39aef9bb5a8279b2a51ae9f536ebd82392c96000e3689a14e3a2c28fb9d23573986

test:
  secret_key_base: b12fb3e54bafc8b09238918a8499f81495f72e70218fca71fea2158646ad4093ba8e2eeba3cace8f04450ee0c6a4cb90a65afdd1fc77ca2b82e81369d42e8ec3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
